-- 코드를 입력하세요

SELECT P.PRODUCT_CODE, SUM(S.SALES_AMOUNT)*P.PRICE SALES
FROM PRODUCT P RIGHT JOIN OFFLINE_SALE S ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY 2 DESC, 1;
/*
SELECT PRODUCT_CODE,
       SUM(SALES_AMOUNT)*PRICE SALES
FROM OFFLINE_SALE S LEFT JOIN PRODUCT P ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE*/