-- 코드를 작성해주세요
/*
SELECT A.FISH_COUNT, B.FISH_NAME
FROM (SELECT COUNT(ID) FISH_COUNT, FISH_TYPE
        FROM FISH_INFO
        GROUP BY FISH_TYPE) A JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
ORDER BY FISH_COUNT DESC;*/

SELECT COUNT(A.FISH_TYPE) FISH_COUNT, B.FISH_NAME
FROM FISH_INFO A JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
GROUP BY B.FISH_NAME
ORDER BY FISH_COUNT DESC;