-- 코드를 입력하세요
/*SELECT HOUR(DATETIME) AS HOUR, COUNT(*) COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
ORDER BY 1;*/

WITH RECURSIVE CTE(N) AS
(
    SELECT 0
    UNION ALL
    SELECT N+1 FROM CTE WHERE N < 23
)
SELECT N AS HOUR, COUNT(ANIMAL_TYPE) COUNT
FROM CTE LEFT JOIN ANIMAL_OUTS ON N = HOUR(DATETIME)
GROUP BY 1
ORDER BY 1;