-- 코드를 작성해주세요
/*SELECT COUNT(*) FISH_COUNT
FROM FISH_INFO A LEFT JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
WHERE A.FISH_TYPE = '0' OR A.FISH_TYPE = '1';*/

SELECT  COUNT(FI.ID) AS FISH_COUNT
FROM    FISH_NAME_INFO FNI 
LEFT JOIN FISH_INFO FI ON FNI.FISH_TYPE = FI.FISH_TYPE
WHERE   FNI.FISH_NAME IN ('BASS','SNAPPER')