-- 코드를 작성해주세요

SELECT A.SCORE, A.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
FROM (SELECT EMP_NO, SUM(SCORE) SCORE
        FROM HR_GRADE
        GROUP BY EMP_NO
        ORDER BY 2 DESC
        LIMIT 1) A JOIN HR_EMPLOYEES B ON A.EMP_NO = B.EMP_NO

/*
SELECT EMP_NO, SUM(SCORE) SCORE
FROM HR_GRADE
GROUP BY EMP_NO
ORDER BY 2 DESC
LIMIT 1;*/
