-- 코드를 입력하세요

SELECT A.CATEGORY, A.MAX_PRICE, B.PRODUCT_NAME
FROM (SELECT CATEGORY, MAX(PRICE) MAX_PRICE
        FROM FOOD_PRODUCT
        WHERE CATEGORY IN ('국', '과자', '김치', '식용유')
        GROUP BY CATEGORY) A JOIN       
    FOOD_PRODUCT B ON A.CATEGORY = B.CATEGORY
WHERE A.MAX_PRICE = B.PRICE
ORDER BY 2 DESC;

/*
SELECT MP.CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT P JOIN (
    SELECT CATEGORY, MAX(PRICE) as MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY) MP
ON P.CATEGORY = MP.CATEGORY
WHERE MP.MAX_PRICE = P.PRICE
ORDER BY MAX_PRICE DESC;*/